// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VKtxe-KKD6MLRZJiH7OTSrUXh0D-bUo',
    appId: '1:746022793614:web:752139c5b586c69e2ef4df',
    messagingSenderId: '746022793614',
    projectId: 'miniproject-f2396',
    authDomain: 'miniproject-f2396.firebaseapp.com',
    storageBucket: 'miniproject-f2396.firebasestorage.app',
    measurementId: 'G-3N5H87D381',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcEAIr6KFOtTkdIoJiFnK_rz96bnC3Iw',
    appId: '1:746022793614:android:e2ee54426dc164782ef4df',
    messagingSenderId: '746022793614',
    projectId: 'miniproject-f2396',
    storageBucket: 'miniproject-f2396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfKOb8ti9Fc95bRBAibLowPNjl2mZHsk',
    appId: '1:746022793614:ios:d0911cea944ddcdd2ef4df',
    messagingSenderId: '746022793614',
    projectId: 'miniproject-f2396',
    storageBucket: 'miniproject-f2396.firebasestorage.app',
    iosBundleId: 'com.example.mathGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGfKOb8ti9Fc95bRBAibLowPNjl2mZHsk',
    appId: '1:746022793614:ios:d0911cea944ddcdd2ef4df',
    messagingSenderId: '746022793614',
    projectId: 'miniproject-f2396',
    storageBucket: 'miniproject-f2396.firebasestorage.app',
    iosBundleId: 'com.example.mathGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VKtxe-KKD6MLRZJiH7OTSrUXh0D-bUo',
    appId: '1:746022793614:web:230acdbddbf4817c2ef4df',
    messagingSenderId: '746022793614',
    projectId: 'miniproject-f2396',
    authDomain: 'miniproject-f2396.firebaseapp.com',
    storageBucket: 'miniproject-f2396.firebasestorage.app',
    measurementId: 'G-5ZFP467WSJ',
  );
}
